// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DEVkEWp08s3fkRbE4zE-LaP77vJ0QEk',
    appId: '1:866140733687:web:440dbab360df4d1592d3f2',
    messagingSenderId: '866140733687',
    projectId: 'hack22-e9ab7',
    authDomain: 'hack22-e9ab7.firebaseapp.com',
    storageBucket: 'hack22-e9ab7.appspot.com',
    measurementId: 'G-5WT2MYEYMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTjhYrMG3lEwdVJvcLRErIODSQ3G0Rpg',
    appId: '1:866140733687:android:907673f89215086692d3f2',
    messagingSenderId: '866140733687',
    projectId: 'hack22-e9ab7',
    storageBucket: 'hack22-e9ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_ze1VUVoDUZNQRRH19YqyntVrDmEcZo',
    appId: '1:866140733687:ios:62940d7d96d4494992d3f2',
    messagingSenderId: '866140733687',
    projectId: 'hack22-e9ab7',
    storageBucket: 'hack22-e9ab7.appspot.com',
    iosClientId: '866140733687-0945kuqeib3amgqumm1t17c55fettmuq.apps.googleusercontent.com',
    iosBundleId: 'com.hack22.app',
  );
}
